language: android
sudo: false         # 开启基于容器的Travis CI任务，让编译效率更高。

android:
  components:
    - build-tools-27.0.3
    - android-27

before_install:
  - chmod +x gradlew

script:
  - ./gradlew assembleDebug

before_deploy:
  - mv app/build/outputs/apk/app-debug.apk app/build/outputs/apk/cimoc.apk