language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-30.0.3
  - android-30
  - add-on
  - extra
licenses:
  - android-sdk-license-.+
before_install:
  - echo $TRAVIS_BUILD_NUMBER
  - yes | sdkmanager "platforms;android-30"
jdk:
- oraclejdk8
before_script:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh && . ./install-jdk.sh -F 11 -L GPL
  - chmod +x gradlew
script:
  #- "./gradlew assembleRelease"
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then ./gradlew assembleDebug; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./gradlew assembleRelease; fi'
before_deploy:
  - echo gitVersion
  - git rev-list --all --count
  - echo version
  - git describe --tags
  - echo $TRAVIS_BUILD_NUMBER
deploy:
  provider: releases
  api_key:
    secure: "$API_KEY"
  file: "app/build/outputs/apk/release/OnlyX.apk"
  skip_cleanup: true
  on:
    repo: onlytheworld/OnlyX
    branch:
      - release-tci
      - dev
    tags: true
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f2c42f2c1f06e4ac7bd0
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always